### ISSUE TITLE
用%llx打印unsigned long long时，高32位始终为0

### ISSUE THREAD

**Issue by zhangboyang** [davidgao/AIM-public#1]
https://github.com/davidgao/AIM-public/blob/1fb45030ed69cdb9176f25a3b6426968100684a1/lib/libc/snprintf.c#L47-L48
应该改为`long long val;
    unsigned long long uval;`

另外貌似libgcc没有链接进去？
https://github.com/davidgao/AIM-public/blob/1fb45030ed69cdb9176f25a3b6426968100684a1/kern/Makefile.am#L52
应该改为？`vmaim_elf_LDADD = libkernel.la $(MODULES) -lgcc`

**Comment by davidgao** [comment]
在386上不加 libgcc 也问题不大，C库函数那边我会去处理

**Comment by zhangboyang** [comment]
64位除法应该会用到libgcc吧。。。如果不加的话，改完的printf应该就挂了。。。

**Comment by davidgao** [comment]
我会处理

**Comment by davidgao** [comment]
Please merge commit c4b26212dfb4b02863882c69435392ecb748ed5f and see if that fixes your problem.
Please close if solved and provide further details otherwise.
